### ISSUE TITLE
Require not included resources

### ISSUE THREAD

**Issue by ssuchanowski** [WrathChaos/react-native-whatsnew-kit#1]
Hey,

You have to remove static data from https://github.com/WrathChaos/react-native-whatsnew-kit/blob/master/lib/src/WhatsNewKit.js#L21 because the images are not added by default to the project.

**Comment by kuraydev** [comment]
Ah thank you so much :) I will fix it and publish a new version.

**Comment by kuraydev** [comment]
Hello @ssuchanowski,
Really sorry for the late release. 

Here is the new release please check it out:
## [Release 0.0.2 🥳](https://github.com/WrathChaos/react-native-whatsnew-kit/releases/tag/0.0.2)
